# https://wandb.ai

wandb:
#  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  _target_: src.utilities.wandb_callbacks.MyWandbLogger
  entity: ds423  # optionally set to name of your wandb team or entity
  name: null   # will be automatically set to the name of the run (plus timestamp, etc.)
  tags: []
  notes: "..."
  project: "DYffusion"  # name of the project in wandb.
  group: ""
  resume: "allow"
  reinit: True
  mode: online              # disabled  # disabled for no wandb logging
  save_dir: ${work_dir}/
  offline: True           # set True to store all logs only locally
  id: null                 # pass correct id to resume experiment!
  log_model: False         # True or 'all'
  prefix: ""
#  job_type: "train"
